apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUServiceConfiguration
metadata:
  name: doca-telemetry-service
  namespace: dpf-operator-system
spec:
  deploymentServiceName: "doca-telemetry-service"
  serviceConfiguration:
    configPorts:
      ports:
        - name: httpserverport
          port: 9189
          protocol: TCP
      serviceType: None
