apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUServiceTemplate
metadata:
  name: hbn
  namespace: dpf-operator-system
spec:
  deploymentServiceName: "hbn"
  helmChart:
    source:
      repoURL: https://helm.ngc.nvidia.com/nvidia/doca
      version: "1.0.2"
      chart: doca-hbn
    values:
      image:
        repository: quay.io/itsoiref/hbn
        tag: 25.4-doca-3.0
      resources:
        memory: 6Gi
        nvidia.com/bf_sf: 3
  resourceRequirements:
    cpu: 6
    memory: 6Gi
    storage: 1Gi
    vfCount: 3